# Generated by Django 3.1.4 on 2020-12-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='room.room'),
            preserve_default=False,
        ),
    ]
