# Generated by Django 3.1.4 on 2020-12-22 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('family', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('code', models.CharField(max_length=9, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('degrees', models.CharField(choices=[('1', 'لیسانس'), ('2', 'فوق لیسانس'), ('3', 'دکترا')], max_length=20)),
                ('studies', models.CharField(choices=[('1', 'ریاضی محض'), ('2', 'ریاضی کاربردی'), ('3', 'کامپیوتر نرم افزار'), ('4', 'کامپیوتر سخت افزار'), ('5', 'روانشناسی')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('family', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('code', models.CharField(max_length=9, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
